version: '3.8'

services:
  # 1. Database (MySQL)
  pfe-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: supadata_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 2. Backend (Spring Boot) - مجلد supadata
  pfe-backend:
    build: ./supadata        # <--- إسم مجلد الـ IntelliJ
    image: pfetest-backend:latest
    container_name: pfe-backend
    restart: always
    depends_on:
      - pfe-db
    ports:
      - "8080:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/supadata_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # 3. Frontend (Client Store) - مجلد frontend
  pfe-frontend:
    build: ./frontend       # <--- إسم مجلد الـ Angular Front
    image: pfetest-frontend:latest
    container_name: pfe-frontend
    restart: always
    ports:
      - "4000:80"
    depends_on:
      - pfe-backend

  # 4. Admin Panel - مجلد Admin
  pfe-admin:
    build: ./Admin          # <--- إسم مجلد الـ Angular Admin (ثبت كان الـ A كبيرة)
    image: pfetest-admin:latest
    container_name: pfe-admin
    restart: always
    ports:
      - "4001:80"
    depends_on:
      - pfe-backend

volumes:
  db_data: