server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # السطر هذا هو اللي يحي مشكلة الـ 404 بعد الـ Login
        try_files $uri $uri/ /index.html;
    }

    # التوجيه للـ Backend (ثبت في البور 8081 واسم السيرفيس)
    location /api/ {
        proxy_pass http://pfe-backend:8081/api/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}